apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
  SPRING_DATASOURCE_USERNAME: petclinic
  SPRING_DATASOURCE_PASSWORD: petclinicpass
